name: .NET

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c release -r debian.11-x64 --self-contained
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Sync files with rsync
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -av
        path: ./DiscordBot/bin/Release/net6.0/debian.11-x64/publish/
        remote_path: /home/${{ secrets.SSH_USER }}/discord-bot/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Trigger Bot Restart
      id: req
      uses: fjogeleit/http-request-action@master
      with:
        url: https://api.taptwice.dev/services/discord-bot/restart?key=${{secrets.API_KEY_SERVICES}}
        method: "GET"
    - name: Show Response
      run: echo ${{ steps.req.outputs.response }}
        
